---
members:
  required: true
  default_value:
  value_type: array
aliases:
  required: false
  default_value:
  value_type: array
domain_membership:
  required: false
  default_value: false
  value_type: boolean
privacy:
  required: false
  default_value: false
  value_type: false 
archive:
  required: false
  default_value: false
  value_type: false 
